% LaTeX file for Chapter 02
<<'preamble02',include=FALSE>>=
library(knitr) 
opts_chunk$set( 
    fig.path='figure/ch02_fig',    
    self.contained=FALSE,
    cache=!FALSE
) 
@

\chapter{Methods} 

For the whole analysis, we were using R version 4.1.2, Rstudio version 1.4.1103 and BiocManager version 3.14.

\section{Reproduction of treekoR Analysis on Age Chronic Dataset}

To use the treekoR package from BiocManager on data, the data must first be converted to a Single Cell Experiment object. According to the treekoR paper's specifications, the count data were transformed using an arcsinh transformation with cofactor 5. The data were then clustered using the FlowSOM-based function cluster() from the CATALYST package. 
FlowSOM uses a self-organising map in order to analyse cytometry data. Its goal is to prevent the potential loss in subset detection that comes with the increasing number of markers measured in cytometry. To this end, it uses two-level clustering and star charts. %cite FlowSOM paper

part I: reproduction of treekoR analysis on Age Chronic (?) data set
- reading in, transforming fsc to sce
- arcsinh transformation with cofactor 5 of count data
- clustering of data using flowSom-based function cluster() from the CATALYST package
- construct cell hierarchy, once using "hopach" and once using "average linkage" algorithm, with function given in treekoR package, provide short explanation of how these these two hierarchical clustering algorithms work
- compute parent as well as total proportions for both hierarchical trees
- significance testing for both proportions
- visualisation for both hierarchies


part II: Benchmarking
- use provided datasets by the author(s) of treekoR
- use their code (provide description of what the code does here)
- on top of balanced accuracy, compute our chosen measure and explain how it is computed